export const customerFieldHelp = {
  specialProject: {
    title: '专项',
    type: 'calc',
    meaning: '当前客户列表固定展示企业彩光 ICT 专项客户池。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'campaign_tag',
    calculation: '客户聚合时写入专项标签，当前筛选控件固定为企业彩光ICT。',
    emptyState: '无专项标签时按默认专项展示。',
  },
  keyword: {
    title: '客户关键词',
    type: 'src',
    meaning: '按客户公司名称进行模糊搜索。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'customer_name',
    calculation: '后端使用 customer_name LIKE 关键字过滤客户列表。',
    emptyState: '未输入时不过滤客户名称。',
  },
  industry: {
    title: '行业',
    type: 'src',
    meaning: '客户所属行业，用于列表筛选和展示。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'industry',
    calculation: '筛选时按 industry 精确匹配；选项来自客户聚合表中的行业去重结果。',
    emptyState: '无行业时显示未知或为空。',
  },
  owner: {
    title: '负责人',
    type: 'src',
    meaning: '客户当前归属负责人或客户经理。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'owner_name',
    calculation: '筛选时按 owner_name 精确匹配；选项来自客户聚合表中的负责人去重结果。',
    emptyState: '无负责人时显示未知或为空。',
  },
  interaction30d: {
    title: '近30天互动',
    type: 'calc',
    meaning: '客户近 30 天内发生的互动次数。',
    sourceTables: 'dws_customer_360、dws_interaction_detail',
    sourceFields: 'dws_customer_360.interaction_count_30d、dws_interaction_detail.event_time',
    calculation: 'ETL 按客户汇总 dws_interaction_detail 中 event_time 在最近 30 天内的记录数，写入 interaction_count_30d；筛选时使用 interaction_count_30d >= 输入值。',
    emptyState: '无近 30 天互动时显示 0。',
  },
  channel: {
    title: '互动方式',
    type: 'calc',
    meaning: '按客户最近互动渠道筛选客户列表。',
    sourceTables: 'dws_customer_360、dws_interaction_detail',
    sourceFields: 'last_interaction_channel、channel',
    calculation: 'ETL 汇总互动明细渠道并写入客户聚合结果；当前列表接口按 last_interaction_channel 精确过滤。',
    emptyState: '未选择时不过滤互动方式；无渠道时显示为空或 -。',
  },
  customerName: {
    title: '客户名称',
    type: 'src',
    meaning: '客户列表展示的标准化公司名称。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'customer_name',
    calculation: '由客户聚合流程按客户名称归并后展示。',
    emptyState: '无公司名时显示样例未提供或为空。',
  },
  projectIndustry: {
    title: '专项/行业',
    type: 'calc',
    meaning: '客户命中的专项标签和所属行业。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'campaign_tag、industry',
    calculation: '专项来自 campaign_tag，行业来自 industry，表格中上下两行展示。',
    emptyState: '无行业时显示未知或为空。',
  },
  purchaseStage: {
    title: '采购阶段',
    type: 'calc',
    meaning: '客户当前所处采购阶段。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'purchase_stage',
    calculation: '客户聚合时根据 CRM 商机阶段、预测类别或线索阶段推导。',
    emptyState: '无法判断阶段时显示 - 或未知。',
  },
  roleCoverage: {
    title: '关键角色覆盖',
    type: 'calc',
    meaning: '客户是否覆盖关键采购角色。',
    sourceTables: 'dws_customer_360、dws_contact_360',
    sourceFields: 'role_coverage、role_category、purchase_role',
    calculation: '按联系人职位、部门或角色标签归类后统计关键角色覆盖情况。',
    emptyState: '无联系人或无法识别角色时显示 -。',
  },
  intent: {
    title: '合作意向',
    type: 'calc',
    meaning: '客户当前合作意向分数、等级和总互动次数。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'intent_score、intent_level、interaction_count_total',
    calculation: '根据近30天互动、在途商机和联系人覆盖计算 intent_score，再映射为高/中/低/无；互动次数展示 interaction_count_total。',
    emptyState: '无意向信号时显示 -。',
  },
  lastInteraction: {
    title: '最近互动',
    type: 'src',
    meaning: '客户最近一次可追溯互动日期和互动方式。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'last_interaction_time、last_interaction_channel',
    calculation: '列表页直接读取客户聚合表字段；日期展示 last_interaction_time 的年月日，互动方式展示 last_interaction_channel 的中文映射。',
    emptyState: '无互动时显示 -。',
  },
}
