const baseTimeRule = '时间筛选取 dws_interaction_detail.event_time；客户无互动但已有 DWS 客户聚合时，仅在未选择时间和渠道时保留。'

export const campaignHelp = {
  total_customers: {
    title: '总客户数',
    type: 'calc',
    path: 'campaign.kpis.total_customers',
    meaning: '当前专项/行业筛选后的去重客户数。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.customer_name, dws_customer_360.campaign_tag, dws_customer_360.industry',
    calculation: '按 dws_customer_360.customer_name 去重；不因时间窗口要求客户存在互动记录。',
    timeRule: '总客户数按客户主表统计，不使用互动时间窗口；有互动行为客户数单独按 dws_interaction_detail.event_time 命中上方时间段。',
    emptyState: '无匹配客户显示 0。',
  },
  active_customers: {
    title: '有互动行为客户数',
    type: 'calc',
    path: 'campaign.kpis.active_customers',
    meaning: '当前筛选条件下至少发生 1 次互动的去重客户数。',
    sourceTables: 'dws_customer_360, dws_interaction_detail',
    sourceFields: 'dws_interaction_detail.customer_name, dws_interaction_detail.channel, dws_interaction_detail.event_time',
    calculation: '客户池内存在互动明细即计 1；渠道筛选仅保留对应 channel。',
    timeRule: '严格按 dws_interaction_detail.event_time 命中上方时间段。',
    emptyState: '无互动显示 0。',
  },
  opportunity_count: {
    title: '商机数',
    type: 'calc',
    path: 'campaign.kpis.opportunity_count',
    meaning: '当前客户池内可追溯商机数量。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.active_opp_count, dws_customer_360.funnel_opp_count',
    calculation: '优先汇总 active_opp_count；为 0 时回退 funnel_opp_count。DWS 当前没有业务机会编码_new，无法按机会编码逐条统计。',
    timeRule: baseTimeRule,
    emptyState: '无商机显示 0。',
  },
  total_amount: {
    title: '总金额',
    type: 'calc',
    path: 'campaign.kpis.total_amount',
    meaning: '当前客户池内在途商机金额合计。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.active_opp_amount',
    calculation: '对筛选后的 active_opp_amount 求和；该字段由商机 amount_10k 转为元后写入，页面按元自动换算为万/亿展示。',
    timeRule: baseTimeRule,
    emptyState: '无金额显示 ¥0.00元。',
  },
  deal_customers: {
    title: '对单客户',
    type: 'calc',
    path: 'campaign.kpis.deal_customers',
    meaning: '当前客户池内已经成交/已下单的去重客户数。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.won_amount, dws_customer_360.purchase_stage',
    calculation: 'won_amount > 0 或 purchase_stage = 阶段6：完成采购，实现进入，则该客户计为对单客户。',
    timeRule: baseTimeRule,
    emptyState: '无对单客户显示 0。',
  },
  opportunity_distribution: {
    title: '商机预测类别分布',
    type: 'calc',
    path: 'campaign.opportunity_distribution',
    meaning: '当前专项/行业全量客户池按 CRM 预测类别的分布。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.forecast_type, dws_customer_360.active_opp_count, dws_customer_360.funnel_opp_count, dws_customer_360.won_amount, dws_customer_360.purchase_stage',
    calculation: '按 forecast_type 分组，并用 won_amount/purchase_stage 识别已下单，用 active_opp_count/funnel_opp_count 识别在途；占比以专项/行业全量客户为分母。',
    timeRule: '商机预测按客户主表的专项/行业客户池统计，不使用互动时间窗口或渠道筛选收窄客户池。',
    emptyState: '无商机或预测类别时显示未标注或暂无数据。',
  },
  channel_attribution: {
    title: '渠道归因',
    type: 'calc',
    path: 'campaign.channel_attribution',
    meaning: '按全量客户最近互动渠道归因统计客户数；非邮件、官网、直播/活动、微信的非空渠道临时合并为其他。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.customer_name, dws_customer_360.last_interaction_channel',
    calculation: '按 last_interaction_channel 分组统计去重客户数；空值归为无渠道/未触达；占比以专项/行业全量客户为分母。',
    timeRule: '渠道归因按客户主表的专项/行业客户池统计，不使用互动时间窗口或渠道筛选收窄客户池。',
    emptyState: '无客户时显示暂无数据。',
  },
  stage_distribution: {
    title: '采购阶段分布',
    type: 'calc',
    path: 'campaign.stage_distribution',
    meaning: '按客户最高采购阶段聚合分布。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.purchase_stage, dws_customer_360.forecast_type',
    calculation: '直接使用 DWS 聚合后的 purchase_stage；未提供阶段时归为未知阶段。',
    timeRule: '采购阶段按客户主表的专项/行业客户池统计，不使用互动时间窗口。',
    emptyState: '无阶段显示未知阶段。',
  },
  role_coverage: {
    title: '关键角色覆盖',
    type: 'calc',
    path: 'campaign.role_coverage',
    meaning: '判断客户是否覆盖拍板者、决策者、评估者、采购推动者四类角色。',
    sourceTables: 'dws_customer_360, dws_contact_360',
    sourceFields: 'dws_customer_360.role_coverage, dws_customer_360.role_detail, dws_contact_360.position, dws_contact_360.department, dws_contact_360.role_category',
    calculation: '本看板直接使用 dws_customer_360.role_coverage 聚合分布；角色明细来自联系人职位/部门归类。',
    timeRule: '角色覆盖按客户主表的专项/行业客户池统计，不使用互动时间窗口。',
    emptyState: '无联系人或无法识别时显示 0/4。',
  },
  tag_signals: {
    title: '标签与痛点信号',
    type: 'calc',
    path: 'campaign.tag_signals',
    meaning: '按客户主表行业字段展示可用客户标签。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.industry, dws_customer_360.campaign_tag',
    calculation: '当前只保留行业标签，例如企业；后续有新的标签字段后再扩展。',
    timeRule: '标签按客户主表的专项/行业客户池统计，不使用互动时间窗口。',
    emptyState: '无关键词时显示暂无信号。',
  },
  content_effect: {
    title: '内容效果',
    type: 'calc',
    path: 'campaign.content_effect',
    meaning: '按互动明细中的内容字段聚合触达、打开、点击、MQL、SQL、成交贡献。',
    sourceTables: 'dws_interaction_detail',
    sourceFields: 'dws_interaction_detail.content, dws_interaction_detail.behavior_type, dws_interaction_detail.is_high_value, dws_interaction_detail.event_time',
    calculation: '内容与内容兴趣均取 content；产品兴趣暂无可靠字段，暂不填充。打开率=打开次数/触达客户数；点击率=点击次数/触达客户数；MQL 用 is_high_value 近似，SQL/成交暂不伪造。',
    timeRule: '取互动发生时间 event_time 命中上方时间段。',
    emptyState: '分母为 0 时率显示 0%。',
  },
  content_interest: {
    title: '内容兴趣',
    type: 'calc',
    meaning: '客户发生互动的内容主题。',
    sourceTables: 'dws_interaction_detail',
    sourceFields: 'dws_interaction_detail.content',
    calculation: '按 content 分组汇总互动记录；当前直接展示该组的 content，按触达客户数、点击数和互动次数排序取前 10 条。',
    timeRule: '取 event_time 命中当前筛选时间段的互动记录。',
    emptyState: 'content 为空的记录不参与统计。',
  },
  product_interest: {
    title: '产品兴趣',
    type: 'calc',
    meaning: '内容互动所体现的产品方向。',
    sourceTables: '当前数据源未接入',
    sourceFields: 'product_interest',
    calculation: '当前互动明细没有可靠的产品兴趣字段，因此不从内容文本推测，待产品兴趣字段接入后按内容分组展示。',
    timeRule: '接入后跟随当前内容效果的时间筛选。',
    emptyState: '当前显示 -。',
  },
  content_open_rate: {
    title: '打开率',
    type: 'calc',
    meaning: '该内容的打开或浏览行为相对触达客户数的比例。',
    sourceTables: 'dws_interaction_detail',
    sourceFields: 'dws_interaction_detail.behavior_type, dws_interaction_detail.content, dws_interaction_detail.customer_name',
    calculation: '打开率 = 打开行为次数 ÷ 去重触达客户数 × 100%；打开行为通过“打开、浏览、触达、PAGE_VIEW”关键词识别。',
    timeRule: '取 event_time 命中当前筛选时间段的互动记录。',
    emptyState: '无触达客户时显示 0%。',
  },
  content_click_rate: {
    title: '点击率',
    type: 'calc',
    meaning: '该内容的点击或高意向动作相对触达客户数的比例。',
    sourceTables: 'dws_interaction_detail',
    sourceFields: 'dws_interaction_detail.behavior_type, dws_interaction_detail.content, dws_interaction_detail.customer_name',
    calculation: '点击率 = 点击行为次数 ÷ 去重触达客户数 × 100%；点击行为通过“点击、下载、提交、咨询、报名、留资、click_”关键词识别。',
    timeRule: '取 event_time 命中当前筛选时间段的互动记录。',
    emptyState: '无触达客户时显示 0%。',
  },
  content_mql: {
    title: 'MQL',
    type: 'calc',
    meaning: '该内容产生的营销合格线索行为数量。',
    sourceTables: 'dws_interaction_detail',
    sourceFields: 'dws_interaction_detail.is_high_value',
    calculation: '按内容分组累计 is_high_value = 1 的互动次数，当前作为 MQL 的近似口径。',
    timeRule: '取 event_time 命中当前筛选时间段的互动记录。',
    emptyState: '无高价值行为时显示 0。',
  },
  content_sql: {
    title: 'SQL',
    type: 'calc',
    meaning: '该内容贡献的销售合格线索数量。',
    sourceTables: '当前数据源未接入',
    sourceFields: 'sql_count',
    calculation: '当前没有内容互动到 SQL 的归因关系，因此固定显示 0；接入线索转化关系后按内容归因统计。',
    timeRule: '接入后跟随当前内容效果的时间筛选。',
    emptyState: '当前显示 0。',
  },
  content_deal: {
    title: '成交',
    type: 'calc',
    meaning: '该内容最终贡献的成交数量。',
    sourceTables: '当前数据源未接入',
    sourceFields: 'deal_count',
    calculation: '当前没有内容互动到成交商机的归因关系，因此固定显示 0；接入内容、线索和商机归因链路后统计。',
    timeRule: '接入后跟随当前内容效果的时间筛选。',
    emptyState: '当前显示 0。',
  },
  customer_followup: {
    title: '客户跟进',
    type: 'calc',
    path: 'campaign.customer_followup',
    meaning: '当前专项/行业全量客户池内分页展示客户推进状态。',
    sourceTables: 'dws_customer_360, dws_interaction_detail',
    sourceFields: 'dws_customer_360.customer_name, dws_customer_360.owner_name, dws_customer_360.purchase_stage, dws_customer_360.intent_score, dws_customer_360.role_coverage, dws_customer_360.last_interaction_time, dws_customer_360.last_interaction_channel',
    calculation: '客户标签由 campaign_tag/attribute/industry/product_categories/source_tables 组合；阶段、负责人、客户名用于筛选；每页展示 10 条。',
    timeRule: '客户跟进按客户主表的专项/行业客户池统计，不使用互动时间窗口或渠道筛选收窄客户池。',
    emptyState: '无互动显示暂无互动，无负责人显示未知。',
  },
  abm_customer_name: {
    title: '客户',
    type: 'src',
    path: 'campaign.followup.customer_name',
    meaning: '客户跟进列表展示的标准客户名称。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.customer_name',
    calculation: '直接展示 DWS 聚合客户名称。',
    timeRule: '跟随当前客户池筛选。',
    emptyState: '缺失时不展示该行。',
  },
  customer_tags: {
    title: '客户标签',
    type: 'calc',
    path: 'campaign.followup.tags',
    meaning: '客户命中的专项、分层、行业、阶段和来源标签。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.campaign_tag, dws_customer_360.attribute, dws_customer_360.industry, dws_customer_360.purchase_stage, dws_customer_360.product_categories, dws_customer_360.source_tables',
    calculation: '拼接可用 DWS 字段；真实需求类型/业务场景/痛点字段缺失，不做源字段展示。',
    timeRule: '跟随当前客户池筛选。',
    emptyState: '缺失时显示 -。',
  },
}

export const getCampaignHelp = key => campaignHelp[key] || {
  title: key,
  type: 'calc',
  meaning: key,
  sourceTables: '-',
  sourceFields: '-',
  calculation: '-',
  timeRule: '-',
  emptyState: '-',
}
