const baseTimeRule = '时间筛选取 dws_interaction_detail.event_time；客户无互动但已有 DWS 客户聚合时，仅在未选择时间和渠道时保留。'

export const campaignHelp = {
  total_customers: {
    title: '总客户数',
    type: 'calc',
    path: 'campaign.kpis.total_customers',
    meaning: '当前专项/行业/渠道/时间筛选后进入观测窗口的去重客户数。',
    sourceTables: 'dws_customer_360, dws_interaction_detail',
    sourceFields: 'dws_customer_360.customer_name, dws_customer_360.campaign_tag, dws_customer_360.industry, dws_interaction_detail.event_time, dws_interaction_detail.channel',
    calculation: '按 dws_customer_360.customer_name 去重；选择渠道或时间时，要求客户在 dws_interaction_detail 中存在对应互动记录。',
    timeRule: baseTimeRule,
    emptyState: '无匹配客户显示 0。',
  },
  active_customers: {
    title: '有互动行为客户数',
    type: 'calc',
    path: 'campaign.kpis.active_customers',
    meaning: '当前筛选条件下至少发生 1 次互动的去重客户数。',
    sourceTables: 'dws_customer_360, dws_interaction_detail',
    sourceFields: 'dws_interaction_detail.customer_name, dws_interaction_detail.channel, dws_interaction_detail.event_time',
    calculation: '客户池内存在互动明细即计 1；渠道筛选仅保留对应 channel。',
    timeRule: '严格按 dws_interaction_detail.event_time 命中上方时间段。',
    emptyState: '无互动显示 0。',
  },
  opportunity_count: {
    title: '商机数',
    type: 'calc',
    path: 'campaign.kpis.opportunity_count',
    meaning: '当前客户池内可追溯商机数量。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.active_opp_count, dws_customer_360.funnel_opp_count',
    calculation: '优先汇总 active_opp_count；为 0 时回退 funnel_opp_count。DWS 当前没有业务机会编码_new，无法按机会编码逐条统计。',
    timeRule: baseTimeRule,
    emptyState: '无商机显示 0。',
  },
  total_amount: {
    title: '总金额',
    type: 'calc',
    path: 'campaign.kpis.total_amount',
    meaning: '当前客户池内在途商机金额合计。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.active_opp_amount',
    calculation: '对筛选后的 active_opp_amount 求和；该字段由商机 amount_10k 转为元后写入，页面按元自动换算为万/亿展示。',
    timeRule: baseTimeRule,
    emptyState: '无金额显示 ¥0.00元。',
  },
  deal_customers: {
    title: '对单客户',
    type: 'calc',
    path: 'campaign.kpis.deal_customers',
    meaning: '当前客户池内已经成交/已下单的去重客户数。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.won_amount, dws_customer_360.purchase_stage',
    calculation: 'won_amount > 0 或 purchase_stage = 阶段6：完成采购，实现进入，则该客户计为对单客户。',
    timeRule: baseTimeRule,
    emptyState: '无对单客户显示 0。',
  },
  opportunity_distribution: {
    title: '商机预测类别分布',
    type: 'calc',
    path: 'campaign.opportunity_distribution',
    meaning: '当前专项窗口内客户按 CRM 预测类别的分布。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.forecast_type, dws_customer_360.active_opp_count, dws_customer_360.funnel_opp_count, dws_customer_360.won_amount, dws_customer_360.purchase_stage',
    calculation: '按 forecast_type 分组，并用 won_amount/purchase_stage 识别已下单，用 active_opp_count/funnel_opp_count 识别在途。',
    timeRule: baseTimeRule,
    emptyState: '无商机或预测类别时显示未标注或暂无数据。',
  },
  channel_attribution: {
    title: '渠道归因',
    type: 'calc',
    path: 'campaign.channel_attribution',
    meaning: '按互动渠道统计官网、直播、邮件、微信等可追溯互动来源。',
    sourceTables: 'dws_interaction_detail',
    sourceFields: 'dws_interaction_detail.channel, dws_interaction_detail.customer_name, dws_interaction_detail.event_time',
    calculation: '按 channel 分组统计互动记录数和去重客户数。当前 DWS 已有 web/wechat/email/event 等 channel。',
    timeRule: '取 dws_interaction_detail.event_time 命中上方时间段。',
    emptyState: '无记录时显示暂无数据。',
  },
  stage_distribution: {
    title: '采购阶段分布',
    type: 'calc',
    path: 'campaign.stage_distribution',
    meaning: '按客户最高采购阶段聚合分布。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.purchase_stage, dws_customer_360.forecast_type',
    calculation: '直接使用 DWS 聚合后的 purchase_stage；未提供阶段时归为未知阶段。',
    timeRule: baseTimeRule,
    emptyState: '无阶段显示未知阶段。',
  },
  role_coverage: {
    title: '关键角色覆盖',
    type: 'calc',
    path: 'campaign.role_coverage',
    meaning: '判断客户是否覆盖拍板者、决策者、评估者、采购推动者四类角色。',
    sourceTables: 'dws_customer_360, dws_contact_360',
    sourceFields: 'dws_customer_360.role_coverage, dws_customer_360.role_detail, dws_contact_360.position, dws_contact_360.department, dws_contact_360.role_category',
    calculation: '本看板直接使用 dws_customer_360.role_coverage 聚合分布；角色明细来自联系人职位/部门归类。',
    timeRule: '角色覆盖本身不按时间过滤；时间筛选只改变客户池。',
    emptyState: '无联系人或无法识别时显示 0/4。',
  },
  tag_signals: {
    title: '标签与痛点信号',
    type: 'calc',
    path: 'campaign.tag_signals',
    meaning: '从 DWS 可用字段中抽取行业、行为和内容主题信号。',
    sourceTables: 'dws_customer_360, dws_interaction_detail',
    sourceFields: 'dws_customer_360.product_categories, dws_customer_360.industry, dws_customer_360.campaign_tag, dws_interaction_detail.content, dws_interaction_detail.behavior_type',
    calculation: '真实痛点/业务场景标签在 DWS 中缺字段；当前用行业、内容、行为类型做降级信号。',
    timeRule: baseTimeRule,
    emptyState: '无关键词时显示暂无信号。',
  },
  content_effect: {
    title: '内容效果',
    type: 'calc',
    path: 'campaign.content_effect',
    meaning: '按内容或互动主题聚合触达、打开、点击、MQL、SQL、成交贡献。',
    sourceTables: 'dws_interaction_detail, dws_customer_360',
    sourceFields: 'dws_interaction_detail.content, dws_interaction_detail.behavior_type, dws_interaction_detail.is_high_value, dws_customer_360.active_opp_count, dws_customer_360.won_amount',
    calculation: 'DWS 无独立内容库、MQL、SQL 和内容归因字段；内容用 content/behavior_type 近似，MQL 用 is_high_value 近似，SQL/成交不伪造源字段。',
    timeRule: '取互动发生时间 event_time；商机归因无法精确到内容时显示 0 或降级说明。',
    emptyState: '分母为 0 时率显示 0%。',
  },
  customer_followup: {
    title: '客户跟进',
    type: 'calc',
    path: 'campaign.customer_followup',
    meaning: '当前专项客户池内按客户汇总最近互动、负责人、商机和建议跟进依据。',
    sourceTables: 'dws_customer_360, dws_interaction_detail',
    sourceFields: 'dws_customer_360.customer_name, dws_customer_360.owner_name, dws_customer_360.purchase_stage, dws_customer_360.intent_score, dws_customer_360.role_coverage, dws_customer_360.last_interaction_time, dws_customer_360.last_interaction_channel',
    calculation: '客户标签由 campaign_tag/attribute/industry/product_categories/source_tables 组合；跟进依据由最近互动、互动次数、商机金额生成。',
    timeRule: baseTimeRule,
    emptyState: '无互动显示暂无互动，无负责人显示未知。',
  },
  abm_customer_name: {
    title: '客户',
    type: 'src',
    path: 'campaign.followup.customer_name',
    meaning: '客户跟进列表展示的标准客户名称。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.customer_name',
    calculation: '直接展示 DWS 聚合客户名称。',
    timeRule: '跟随当前客户池筛选。',
    emptyState: '缺失时不展示该行。',
  },
  customer_tags: {
    title: '客户标签',
    type: 'calc',
    path: 'campaign.followup.tags',
    meaning: '客户命中的专项、分层、行业、阶段和来源标签。',
    sourceTables: 'dws_customer_360',
    sourceFields: 'dws_customer_360.campaign_tag, dws_customer_360.attribute, dws_customer_360.industry, dws_customer_360.purchase_stage, dws_customer_360.product_categories, dws_customer_360.source_tables',
    calculation: '拼接可用 DWS 字段；真实需求类型/业务场景/痛点字段缺失，不做源字段展示。',
    timeRule: '跟随当前客户池筛选。',
    emptyState: '缺失时显示 -。',
  },
}

export const getCampaignHelp = key => campaignHelp[key] || {
  title: key,
  type: 'calc',
  meaning: key,
  sourceTables: '-',
  sourceFields: '-',
  calculation: '-',
  timeRule: '-',
  emptyState: '-',
}
